version: '3.9'

services:
  movez-chat:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - REDIS_HOST=redis-db
      - REDIS_PORT=6379
    ports:
      - "3000:3000"

  redis-db:
    image: redis:latest
    ports:
      - "6379:6379"
